- name: Set up Node
  uses: actions/setup-node@v3
  with:
    node-version: '18'

- name: Install dependencies
  run: npm install
  working-directory: ./projekt/frontend

- name: Build app
  run: npm run build
  working-directory: ./projekt/frontend
  env:
    VITE_BASEURL: ${{ secrets.VITE_BASEURL }}

- name: Deploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_GROUND_074B6BA03 }}
    action: "upload"
    app_location: "./projekt/frontend"
    output_location: "dist"
